# Site Info
title:              "Jerguš Lejko"
description:        "Fix. Save. Refresh. Fix again. Save. Refresh. Really fix this time. Save. Refresh. Refresh. Refresh. Give up..."
google_analytics:   UA-98190071-1

# Author Info
author_name:        "Jerguš Lejko"
author_email:       jergus.lejko@gmail.com
author_gravatar:    108b69ef6b4f23ced9c53e268b7973f7
twitter_username:   jerguslejko
github_username:    jerguslejko

# Site Settings
baseurl:            ""
permalink:          /post/:title
timezone:           Europe/London

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
