# Site Info
title:              "Jergus The Developer"
description:        "Fix. Save. Refresh. Fix again. Save. Refresh. Really fix this time. Save. Refresh. Refresh. Refresh. Give up..."
google_verify:      t00Ncu6lq0kpjgVkqKSZjoXOTDh98a-ODh8JbQGUpTc
google_analytics:   UA-98190071-1

# Author Info
author_name:        "Jergus Lejko"
author_email:       jergus.lejko@gmail.com
author_gravatar:    108b69ef6b4f23ced9c53e268b7973f7
twitter_username:   jerguslejko
github_username:    jerguslejko

# Site Settings
baseurl:            ""
permalink:          /posts/:title
timezone:           Europe/London
mathjax:            false

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
